//
//  LocalizationTables.swift
//  Sapphire
//
//  Created by Sapphire Localization Team.
//

import Foundation

// MARK: - Chinese Translations

enum ChineseTranslations {
    static let table: [String: String] = [
        "General": "通用",
        "Notch": "刘海 / 灵动岛",
        "Widgets & Content": "小组件与内容",
        "System & Utilities": "系统与实用工具",
        "Focus & Security": "专注与安全",
        "About": "关于",
        "Keyboard Shortcuts": "键盘快捷键",
        "Bluetooth Unlock": "蓝牙靠近解锁",
        "Authentication": "认证与解锁",
        "Intelligence": "AI 智能助理",
        "Blip": "AI 助理 (Blip)",
        "Nearby Share": "隔空分享 (Nearby)",
        "Continuity": "跨端互联",
        "Android Continuity": "跨端互联 (Android)",
        "Appearance": "外观与动效",
        "Widgets": "小组件管理",
        "Live Activities": "实时活动",
        "Lock Screen": "锁定屏幕",
        "Notifications": "通知管理",
        "HUD": "系统指示器 (HUD)",
        "Music": "音乐与歌词",
        "Weather": "天气预报",
        "Calendar": "日历日程",
        "Sports": "体育赛事",
        "Finance": "财经股票",
        "Battery": "电池与电源管理",
        "Audio": "音频混音与 EQ",
        "Bluetooth": "蓝牙外设",
        "Shortcuts": "快捷指令",
        "File Shelf": "文件暂存架",
        "Notes": "便签备忘录",
        "Clipboard": "剪贴板历史",
        "Mirror": "屏幕镜像",
        "Caffeinate": "防休眠保持唤醒",
        "System Enhance": "系统交互增强",
        "Snap Zones": "窗口吸附分屏",
        "Dock Layouts": "程序坞布局",
        "Dock": "程序坞",
        "Media Optimizer": "媒体性能优化",
        "Mouse": "鼠标与滚轮",
        "Monitoring": "硬件状态监控",
        "Dev Activity": "开发者活动监测",
        "Emoji": "表情符号面板",
        "Archives": "压缩包与 DMG 管理",
        "Archives & DMG": "压缩包与 DMG",
        "Apps": "应用程序管理",
        "Storage": "磁盘存储分析",
        "Eye Break": "护眼休息提醒",
        "Focus Session": "专注番茄钟",
        "Focus Sessions": "专注模式",
        "Focus": "专注模式",
        "App Lock": "应用访问锁",
        "Spacer": "占位间距",
        "Multi-Audio (Beta)": "多应用音量 (Beta)",
        "Pin": "固定置顶",
        "Search settings": "搜索设置项...",
        "Quit": "退出 Sapphire",
        "Select a category": "请在左侧选择一个设置分类",
        "Behavior": "交互行为",
        "General Behavior": "基本行为",
        "Expand on Hover": "鼠标悬停自动展开",
        "Hover Delay": "悬停响应延迟",
        "Click to Expand": "点击刘海展开",
        "Swipe to Switch Widgets": "滑动手势切换小组件",
        "Allow in Apps": "在指定应用中生效",
        "Browsers (Disabled by Default)": "浏览器（默认禁用）",
        "Hover State": "悬停状态",
        "Gestures": "触控手势",
        "Delays": "延迟与响应",
        "System": "系统选项",
        "Language": "显示语言",
        "Language & Region": "语言与地区",
        "Choose the display language for Sapphire.": "选择 Sapphire 应用界面的显示语言，即时生效。",
        "Launch at Login": "开机自动启动",
        "Start Sapphire automatically when you log in to your Mac.": "在您登录 Mac 时自动在后台启动 Sapphire。",
        "Enable Haptic Feedback": "触控板触觉反馈",
        "Provide tactile feedback for certain interactions.": "在展开刘海或完成吸附分屏等交互时提供触觉震动反馈。",
        "Hide from Screen Sharing": "屏幕共享时自动隐藏",
        "Never include Sapphire in screen sharing, screenshots, or screen recordings.": "在录屏、截屏或屏幕共享会议中自动隐藏刘海窗口，保护隐私。",
        "Google Analytics": "匿名使用统计",
        "Send anonymous usage events to Google to help improve Sapphire. Disable this to opt out of analytics collection.": "向开发团队发送匿名使用数据以改进产品质量。您可以随时关闭此选项。",
        "Swipe to Hide Notch": "轻扫隐藏刘海",
        "When the notch is collapsed, swipe up over it to hide it completely. Swipe down near the notch area to bring it back.": "刘海折叠时，向上轻扫可将其完全隐藏；在顶部区域向下轻扫可恢复显示。",
        "Don't Expand While Locked": "锁屏状态禁止展开",
        "Prevent hover, click, and swipe from expanding the notch while the Mac is locked.": "当 Mac 处于锁定状态时，阻止通过鼠标或触控板展开刘海。",
        "Show Notch On": "刘海显示位置",
        "Choose which display Sapphire should attach to when multiple screens are connected.": "当连接多台显示器时，选择 Sapphire 附加到的屏幕目标。",
        "Floating Island on Notchless Displays": "无硬件刘海屏幕显示悬浮岛",
        "Use a rounded island separated from the top edge on Macs and displays without a hardware notch.": "在没有物理凹槽的外接显示器或较老款 Mac 上，以圆角悬浮灵动岛形式显示。",
        "Island Top Offset": "悬浮岛顶部间距",
        "Distance from the top edge on notchless displays.": "在无硬件刘海的屏幕上距离屏幕顶部边缘的距离。",
        "Primary Display": "主显示器",
        "Built-in Display": "内建显示器",
        "External Display": "外接显示器",
        "All Displays": "所有显示器",
        "MacBook Display Only": "仅 MacBook 内建屏",
        "Main Display Only": "仅主显示器",
        "Bounce when Opening Widgets": "打开小组件时回弹动画",
        "Lock Cursor Horizontally with Caps Lock": "使用大写锁定键锁定光标水平移动",
        "Notch Dimensions": "刘海尺寸几何",
        "Notch Width": "刘海宽度",
        "Notch Height": "刘海高度",
        "Corner Radii": "圆角半径",
        "Liquid Glass": "液态玻璃",
        "Liquid Glass Look": "液态玻璃外观",
        "Liquid Glass Effect": "液态玻璃特效",
        "Liquid Glass Style": "液态玻璃材质样式",
        "Frosted Overlay": "磨砂毛玻璃覆盖层",
        "Color & Materials": "颜色与材质",
        "Blur & Shadow": "模糊与阴影",
        "Fade Bottom Edge": "底部边缘透明渐变",
        "Top Offset": "顶部偏移行距",
        "Screen Corners": "屏幕圆角",
        "Screen Corner Radius": "屏幕圆角半径",
        "Hiding Appearance": "隐藏外观",
        "Preset": "预设方案",
        "Match Hardware": "匹配硬件尺寸",
        "Sizing & Position": "尺寸与位置",
        "Configuration": "高级配置",
        "Notch Bar": "刘海栏",
        "Notch Bar Items": "刘海快捷项",
        "Widget Visibility & Order": "小组件可见性与排序",
        "Active Widgets": "当前启用的小组件",
        "Available Widgets": "待添加小组件",
        "Show Dividers Between Widgets": "小组件间显示分割细线",
        "Ignore Widget Space Limit": "解除小组件数量空间限制",
        "Show in Notch": "在刘海中显示",
        "Show on Hover": "鼠标悬停时显示",
        "Show on Click": "点击刘海时显示",
        "Hide When Inactive": "非活动时自动隐藏",
        "Added to Widget": "已添加到小组件",
        "Global Widget Style": "全局小组件样式",
        "Shortcuts Widget": "快捷指令小组件",
        "Activity Visibility & Order": "实时活动可见性与排序",
        "Persistent Activity": "常驻实时活动",
        "Hide All in Full Screen": "全屏应用时隐藏所有活动",
        "Show compact focus live activity text": "显示紧凑专注文本",
        "Show compact battery live activity": "显示紧凑电池电量",
        "Show Lyrics in Live Activity": "在实时活动中展示歌词",
        "Show Bluetooth Live Activity": "显示蓝牙外设活动",
        "Daily Activity": "今日活动统计",
        "Live Activity": "实时活动",
        "Show Notch on Lock Screen": "锁屏界面显示刘海岛",
        "Show Info Widget(s)": "显示顶部信息小组件",
        "Show Main Widget(s)": "显示主小组件",
        "Show Mini Widget(s)": "显示迷你小组件",
        "Show Music When Paused": "暂停时依然保持音乐显示",
        "Custom Lock Screen Wallpaper": "自定义锁屏动态壁纸",
        "Custom Desktop Wallpaper": "自定义桌面壁纸",
        "Hide Wallpaper": "隐藏壁纸",
        "Pause in Low Power Mode": "低电量模式下暂停动画",
        "Pause on Battery Power": "电池供电时暂停动画",
        "Lock & Unlock Actions": "锁屏与解锁交互",
        "Now Playing": "正在播放",
        "Lyrics": "实时同步歌词",
        "Show Now Playing From": "接收播放信息的音乐源",
        "Spotify (Official API)": "Spotify (官方 API)",
        "Spotify (Private API)": "Spotify (私有 API)",
        "TIDAL": "TIDAL",
        "Allow Lyrics From:": "允许提供歌词的来源：",
        "Generate Word-by-Word Timing": "生成逐字/音节级精确时间轴",
        "Hide Music Widget": "无媒体播放时自动隐藏音乐",
        "Hide Paused Spotify Song": "Spotify 暂停时隐藏",
        "Show Album Art": "显示专辑封面图片",
        "Customize Player Buttons": "自定义播放器控制按键",
        "Two-Finger Tap to Play/Pause": "触控板双指轻点播放/暂停",
        "Swipe Left to Skip": "向左轻扫切换下一首",
        "Swipe Right to Rewind": "向右轻扫切换上一首",
        "Waveform Appearance": "音频频谱动效外观",
        "Use Static Waveform": "使用静态律动波形",
        "Enable Gradient": "根据封面生成色彩渐变",
        "Persist Music Widget": "持续常驻音乐小组件",
        "Next Song": "下一首歌曲",
        "Next Song Album Art": "下一首专辑封面",
        "Suggested Songs": "推荐曲目",
        "Artist Profile": "艺术家主页",
        "Concert Tickets": "巡演演出资讯",
        "Play": "播放",
        "Pause": "暂停",
        "Next Track": "下一首",
        "Previous Track": "上一首",
        "Volume": "音量",
        "Battery Level": "电池电量",
        "Battery Management Features": "电池健康与充电管理",
        "Battery Calibration": "电池充放电校准",
        "Charging & Sleep": "充电与睡眠控制",
        "Sailing Mode": "帆航养护模式 (Sailing Mode)",
        "Heat Protection": "过热保护降温",
        "Automatic Discharge": "自动放电至保护电量",
        "One-Time Discharge": "单次放电目标",
        "Stop charging when sleeping": "Mac 睡眠时停止充电",
        "Stop charging when app closed": "Sapphire 退出时停止充电",
        "Disable Sleep until Charge Limit": "充至指定上限前阻止睡眠",
        "Prompt to Turn on Low Power Mode": "低电量时提示开启节能模式",
        "Use Hardware Battery Percentage": "读取真实硬件电池百分比",
        "Log battery during sleep": "记录睡眠期间的电池功耗日志",
        "Fan Control": "风扇转速控制",
        "Custom Fan Curve": "自定义风扇转速温控曲线",
        "Notify for Low Battery": "低电量弹窗通知提醒",
        "Play Sound for Low Battery Alert": "低电量时发出提示音",
        "Charging": "正在充电",
        "Fully Charged": "已充满电",
        "On Battery": "正在使用电池供电",
        "Power Adapter": "电源适配器已连接",
        "Health": "健康度",
        "Per-App Volume Uses System Volume Ceiling": "应用独立音量受系统总音量上限约束",
        "Exclude Built-in Speakers": "排除内建扬声器",
        "Ambient Sounds": "自然白噪音与环境音",
        "Equalizer": "多段均衡器 (EQ)",
        "AutoEQ": "AutoEQ 知名耳机校准曲线",
        "Output Device": "音频输出设备",
        "Mute system audio when nearly closed": "屏幕接近闭合时静音所有系统音频",
        "Pause media when nearly closed": "屏幕接近闭合时自动暂停媒体播放",
        "Sleep display when nearly closed": "屏幕接近闭合时关闭显示器",
        "Enable Low Power Mode as lid closes": "屏幕合上时自动开启低电量模式",
        "Global Default Layout": "全局默认吸附布局",
        "Available Layouts": "可选分屏布局",
        "My Custom Layouts": "我的自定义布局方案",
        "Activate on Drag": "窗口靠近屏幕边缘时触发分屏",
        "Activate on Window Drag": "拖动窗口时显示分屏热区",
        "Padding": "分屏边距与间隙",
        "Planes": "多屏布局面 (Planes)",
        "Selected Layouts (Drag to Reorder)": "已选布局（拖拽调整顺序）",
        "Expand Shelf on Hover": "鼠标悬停自动展开置物架",
        "Remove File After Drag Out": "拖出文件后自动从架上移除",
        "Drop Destinations": "拖放传输目标",
        "Share to Devices": "隔空投送至附近设备",
        "Auto-Clear Clipboard": "自动清空剪贴板",
        "Enable Auto-Clear": "启用自动定时清空",
        "Clear After a Delay": "复制后指定延迟自动清空",
        "Clear When Mac Sleeps": "Mac 睡眠时清空剪贴板",
        "Clear When Screen Locks": "屏幕锁定时清空剪贴板",
        "Clean URL": "网址追踪参数过滤",
        "Clean Copied Links": "自动去除复制链接中的跟踪参数 (utm, fbclid)",
        "Clean Automatically on Copy": "复制链接时自动净化",
        "Paste as Plain Text": "以纯文本形式粘贴",
        "Paste Images as PNG Files": "复制的图片粘贴为 PNG 文件",
        "F2 Renames the Selection": "按 F2 重命名选中的文件",
        "Finder Cut & Paste": "访达剪切与粘贴增强 (⌘X / ⌘V)",
        "Text Snippets": "常用文本短语快捷输入",
        "Quick Picker": "全局浮动剪贴板与表情面板",
        "Monitor Clipboard": "持续监听剪贴板历史",
        "Eye Break Status": "护眼休息状态",
        "Eye Health Recommendations": "护眼健康指南",
        "Weekly Eye Break Activity": "每周护眼打卡记录",
        "Enable Eye Break Reminders": "启用 20-20-20 护眼休息提醒",
        "Play Sound Alerts": "休息开始与结束发出提示声",
        "Block During Breaks": "休息期间遮罩锁定屏幕",
        "Enable Blocking": "专注期间屏蔽分心应用与网址",
        "New Focus Schedule": "新建专注日程计划",
        "Task History": "历史专注时段记录",
        "Break & Session Notifications": "休息与专注时段推送通知",
        "Keep Caffeinate Enabled After Clamshell": "合盖后继续保持防休眠唤醒状态",
        "Prevent Sleep in Clamshell Mode": "合盖使用外接屏时阻止系统睡眠",
        "Black out display using lid angle": "根据屏幕开合角度黑屏节能",
        "HUD Appearance": "指示器外观",
        "Volume HUD": "音量指示器",
        "Brightness HUD": "亮度指示器",
        "Show Dots": "以点阵序列代替进度长条",
        "Show Spotify Device in HUD": "HUD 中显示当前 Spotify 播放设备",
        "Show App Volume in HUD": "在常规 HUD 中显示单 App 音量",
        "Show Device Icon Instead of Speaker": "显示设备专属图标代替普通喇叭",
        "Green Button Maximize": "绿灯全屏按钮改为窗口最大化",
        "Maximize in Current Space": "在当前桌面空间内最大化窗口",
        "Quit & Close Protection": "防误触退出与关闭窗口保护",
        "Protect ⌘Q (Quit)": "长按或双击 ⌘Q 才能退出应用",
        "Protect ⌘W (Close Window)": "长按或双击 ⌘W 才能关闭窗口",
        "Quit on Close": "关闭最后窗口时彻底退出 App",
        "Quit Apps When Their Last Window Closes": "在最后一个窗口关闭后自动退出 App",
        "Dim Inactive Apps": "暗化背景非活动应用窗口",
        "Limit Visible Apps": "限制前台同时显示的 App 数量",
        "App Switching": "增强型 App 切换器",
        "Include Windows From Other Spaces": "包含其他桌面空间中的窗口",
        "Smart Inbox": "智能短信与验证码提取",
        "Enable Smart Inbox": "启用智能收件箱",
        "Scan Mail for OTP codes": "扫描邮件中的一次性验证码 (OTP)",
        "Auto-copy verification codes": "检测到验证码时自动复制到剪贴板",
        "Show copy button for detected codes": "在通知弹窗中显示「一键复制」按钮",
        "Only show notifications with verification codes": "仅在包含验证码时弹出通知",
        "Parcel tracking from email": "自动提取邮件中的快递物流单号",
        "OTP notch popover": "刘海气泡显示验证码",
        "Parcel notch popover": "刘海气泡显示快递状态",
        "Widget Transitions": "小组件切换动画",
        "Control the visual effects when switching between widgets inside the expanded notch.": "控制在展开的刘海内切换小组件时的视觉过渡效果。",
        "Enable Fade Effect": "启用渐隐渐现效果",
        "Enable Slide Effect": "启用滑动切换效果",
        "Enable Bounce Effect": "启用弹性过渡效果",
        "Animation Profile": "全局动效预设",
        "Snappy": "轻快极速 (Snappy)",
        "Bouncy": "灵动弹性 (Bouncy)",
        "Calm": "平缓优雅 (Calm)",
        "Custom": "自定义调节 (Custom)",
        "Custom Animation Values": "自定义动画参数",
        "Reset to Defaults": "重置为默认值",
        "Response: How long the animation takes (lower is faster).\\\\nDamping: How much bounce (1.0 is no bounce).": "响应时间 (Response): 动画时长（数值越低越快）。\\\\n阻尼 (Damping): 弹跳程度（1.0 表示无回弹）。",
        "Main Transitions": "主窗口过渡",
        "Dynamic States": "动态状态变化",
        "Content & Activities": "内容与实时活动",
        "The default. A quick and responsive feel with minimal bounce.": "默认预设。快速响应，带有极微小的回弹感。",
        "A playful and energetic animation with noticeable bounce.": "生动有趣的弹动动画，带有明显的回弹质感。",
        "A slower, more graceful animation with a very gentle ease.": "节奏更柔和、更优雅平缓的缓动动画。",
        "Fine-tune every animation parameter to your exact liking.": "自由微调每一项动画过渡与物理阻尼参数。",
        "Expand Response": "展开响应时间",
        "Expand Damping": "展开阻尼",
        "Opening the main widget view.": "展开主小组件视图时的动画。",
        "Collapse Response": "收起响应时间",
        "Collapse Damping": "收起阻尼",
        "Closing the main widget view.": "收起主小组件视图时的动画。",
        "Swipe Open Response": "轻扫展开响应时间",
        "Swipe Open Damping": "轻扫展开阻尼",
        "Opening the widget with a trackpad swipe.": "使用触控板轻扫展开时的动画。",
        "Hover Response": "悬停响应时间",
        "Hover Damping": "悬停阻尼",
        "The small expansion when hovering over the notch.": "鼠标悬停在刘海上时的微展开动效。",
        "Auto-Expand Response": "自动展开响应时间",
        "Auto-Expand Damping": "自动展开阻尼",
        "When a Live Activity appears automatically.": "实时活动自动弹出时的展开动效。",
        "Content Transition Response": "内容过渡响应时间",
        "Content Transition Damping": "内容过渡阻尼",
        "How widgets appear inside the expanded view.": "展开视图中小组件内容的入场动效。",
        "Activity Switch Response": "活动切换响应时间",
        "Activity Switch Damping": "活动切换阻尼",
        "Transitioning between different Live Activities.": "在不同实时活动之间切换时的过渡动画。",
        "Activity Morph Response": "活动形变响应时间",
        "Activity Morph Damping": "活动形变阻尼",
        "Smoothly changing the shape of a Live Activity.": "平滑改变实时活动胶囊形状的动画。",
        "Advanced Customization": "高级几何定制",
        "Enable Custom Notch Configuration": "启用自定义刘海参数",
        "Override default appearance and animation values. This may lead to unexpected behavior.": "覆盖默认的刘海尺寸与动画参数（修改不当可能导致显示异常）。",
        "Edit Custom Configuration": "编辑自定义配置",
        "Google Gemini API": "Google Gemini API 设置",
        "Configure your Google Gemini API key to enable live voice and screen-sharing AI inside the notch.": "配置您的 Google Gemini API Key，即可在刘海中直接开启屏幕共享与实时语音 AI 交互。",
        "Gemini API Key": "Gemini API 密钥",
        "Configured": "已配置",
        "Not Configured": "未配置",
        "Clear": "清空",
        "Keys are stored securely in your macOS Keychain.": "API 密钥加密保存在 macOS 系统钥匙串中，安全可靠。",
        "Get Free Gemini API Key →": "免费获取 Gemini API 密钥 →",
        "Gemini Live Model": "Gemini 实时多模态模型",
        "Select the multimodal model used for real-time voice and screen interaction.": "选择用于屏幕实时感知与语音问答的多模态模型。",
        "Assistant Voice": "AI 助手发音音色",
        "Choose the voice persona for Gemini Live responses.": "选择 Gemini Live 语音应答的声音音色风格。",
        "Additional AI Providers": "其他 AI 提供商 API",
        "Configure optional API keys for OpenAI, Anthropic Claude, and OpenRouter.": "配置可选的 OpenAI、Anthropic Claude 和 OpenRouter API 密钥。",
        "OpenAI API Key": "OpenAI API 密钥",
        "Anthropic Claude API Key": "Anthropic Claude API 密钥",
        "OpenRouter API Key": "OpenRouter API 密钥",
        "System Instruction (Prompt)": "系统提示词 (Prompt)",
        "Customize how the AI assistant behaves and responds when analyzing your screen.": "自定义 AI 助手在分析您的屏幕和回答问题时的行为人设与要求。",
        "Leave empty to use Sapphire's default concise voice assistant prompt.": "留空则使用 Sapphire 默认的简明精准语音助手人设提示词。",
        "Reset to Default": "恢复默认提示词",
        "Export Backup": "导出配置备份",
        "Restore Backup": "导入恢复备份",
        "Start Fresh": "重置默认设置",
        "Restore all Sapphire preferences to their defaults.": "将 Sapphire 的所有偏好设置恢复为默认值。",
        "Reset Settings": "重置所有设置",
        "Reset all settings?": "确认重置所有设置？",
        "This will replace your current preferences across the app.": "此操作将替换您在应用中的所有现有配置。",
        "Release Channel": "更新发布通道",
        "Choose which update channel to receive releases from.": "选择接收正式稳定版或抢先测试版的更新通道。",
        "Permissions Overview": "系统权限总览",
        "Settings Backup": "配置备份与恢复",
        "Show Launchpad": "打开启动台",
        "Quit Sapphire": "退出 Sapphire",
        "Device Name": "设备名称",
        "Download Location": "文件保存位置",
        "Ready to Receive": "等待接收文件中...",
        "Receiving": "正在接收",
        "Completed": "传输已完成",
        "Done": "完成",
        "Cancel": "取消",
        "Save": "保存",
        "Reset": "恢复默认",
        "Apply": "应用",
        "Settings": "设置",
        "Enabled": "已启用",
        "Disabled": "已禁用",
        "Open": "打开",
        "Close": "关闭",
        "Copy": "复制",
        "Copied": "已复制",
        "Search": "搜索",
        "Version": "版本",
        "Check for Updates": "检查更新",
        "Restart Required": "需要重启应用以完全生效",
        "Restart Now": "立即重启",
        "Later": "稍后",
        "Advanced": "高级选项",
        "Account Badge": "账户徽标",
        "Activity Statistics": "活动统计分析",
        "AirDrop": "隔空投送 (AirDrop)",
        "Allow Notifications From:": "允许接收通知的应用：",
        "Animation (Springs)": "弹簧物理动画",
        "App-Specific Overrides": "应用独立覆盖配置",
        "Auto-Rehide": "自动重新隐藏",
        "Automatic update checks": "自动检查软件更新",
        "Automatically Rehide Items": "自动重新隐藏菜单栏项",
        "Available Shortcuts": "可用快捷键",
        "Calendar & Reminders": "日历与提醒事项",
        "Calendar Integration": "日历集成",
        "Calibrate RSSI Range": "校准蓝牙近场 RSSI 信号范围",
        "Calibration Complete": "校准完成",
        "Click to Show Detail View": "点击展示详情视图",
        "Control Item Icons": "控制项图标样式",
        "Custom Notch Configuration": "自定义刘海高级参数",
        "Displays": "显示器设置",
        "Download verified updates automatically": "自动下载已验证的安全更新",
        "Edit Shortcut": "编辑快捷键",
        "Enable Always-Hidden Section": "启用永久隐藏分区",
        "Enable Automatic Discharge": "启用电池自动放电保健康",
        "Enable Bluetooth Unlock": "启用蓝牙设备靠近解锁",
        "Enable Breaks": "启用休息提醒",
        "Enable Calendar Live Activity": "启用日历日程实时活动",
        "Enable Calendar Widget": "启用日历日程小组件",
        "Enable Clipboard Widget": "启用剪贴板小组件",
        "Enable Face ID Unlock": "启用人脸识别解锁",
        "Enable Finder Shortcuts": "启用访达常用快捷键",
        "Enable Hold Actions": "启用长按快捷交互",
        "Enable Menu Bar Icon Hiding": "启用菜单栏图标收纳隐藏",
        "Enable Menu Bar Profiles": "启用菜单栏情景预设配置",
        "Enable Mirror Widget": "启用镜像小组件",
        "Enable Notes Widget": "启用便签备忘小组件",
        "Enable Quick Picker": "启用浮动快捷选择器",
        "Enable Text Snippets": "启用文本常用短语替换",
        "Enable Translation": "启用实时翻译",
        "Enable Transparency Blur": "启用半透明磨砂背景模糊",
        "Enable track info on Hover": "鼠标悬停时显示歌曲曲目详情",
        "Expand After Space or Punctuation": "输入空格或标点后自动展开短语",
        "Find Device by Distance": "按蓝牙信号距离查找设备",
        "Flip Horizontally": "画面水平翻转镜像",
        "Global Multi-View Layouts": "全局多窗口布局",
        "Hide Main Control Icon": "隐藏主控状态栏图标",
        "Hide When Source App is Active": "原播放应用在前台时自动隐藏",
        "Hide notch when inactive (this display)": "在此显示器闲置时隐藏刘海",
        "Hold Actions": "长按交互操作",
        "Icon Hiding": "状态栏图标收纳",
        "Ignore Concealed Items": "忽略折叠隐藏项",
        "Input Behavior": "输入法与键盘行为",
        "Installed app notifications": "已安装应用的更新推送通知",
        "Invert Swipe Gestures": "反转轻扫滑动手势方向",
        "Live Canvas Video": "Canvas 动态视频背景",
        "Main Widget(s)": "主显示小组件",
        "Menu Bar Profiles": "菜单栏情景配置",
        "Menu Bar Spacing (Beta)": "菜单栏间距调整 (Beta)",
        "Menu Bar Style (Beta)": "菜单栏风格与着色 (Beta)",
        "Menu Bar Tint": "菜单栏着色效果",
        "Mini Widgets": "迷你次级小组件",
        "Monitor installed apps": "后台监控已安装应用的新版本",
        "New Scheduled Task": "新建计划任务",
        "No History Data": "暂无历史记录数据",
        "Notifications & Live Activity": "通知与实时活动配置",
        "Only Show When Usage is High": "仅在硬件资源占用偏高时显示",
        "Open Calendar on Click": "点击打开日历视图",
        "Open Clipboard on Click": "点击打开剪贴板管理器",
        "Open Mirror on Click": "点击全屏展开镜像摄像头",
        "Open Notes on Click": "点击打开便签编辑器",
        "Open Shelf on Live Activity Click": "点击实时活动打开文件暂存架",
        "Passive Mode": "被动扫描节能模式",
        "Pause in Mission Control": "进入调度中心 (Mission Control) 时暂停",
        "Per-Display Overrides": "各显示器独立覆盖参数",
        "Play Connection Sounds": "设备连接与断开播放提示音",
        "Prefer airplay over spotify devices": "优先使用隔空播放 (AirPlay) 设备",
        "Prioritize Selected Source": "优先展示选定的播放源",
        "Profiles": "配置方案",
        "Protect Quit and Close Shortcuts": "快捷键防误触保护",
        "Proximity & Face Unlock": "靠近感知与人脸解锁",
        "Release Notes": "版本更新日志",
        "Remember Last Open Menu": "记住上次打开的展开菜单",
        "Remove Emojis": "过滤纯文本中的 Emoji 表情",
        "Remove Links": "过滤纯文本中的超链接",
        "Remove List Markers": "去除列表无序标号与缩进",
        "Required Permissions": "运行所需系统权限",
        "Reset & Data": "重置与数据管理",
        "Reviewed app cleanup": "已审核应用卸载残留清理",
        "Sapphire": "Sapphire",
        "Schedule Automation": "定时自动化任务",
        "Scheduled Tasks": "已配置计划任务",
        "Scheduling": "自动化调度",
        "Select Custom Range": "选择自定义参数区间",
        "Select Icon": "选择展示图标",
        "Shopify Orders": "Shopify 实时订单跟踪",
        "Show Activity Graph": "显示活动历史趋势图表",
        "Show Caffeinate in Notch Bar": "在刘海栏中显示防休眠按钮",
        "Show Clipboard in Notch Bar": "在刘海栏中显示剪贴板快捷入口",
        "Show Continuity Devices": "显示跨端互联的 Android 手机",
        "Show Device Name": "显示已连接设备的自定义名称",
        "Show Estimated Time Remaining": "显示预估充满/耗尽剩余时间",
        "Show Function Name": "显示按键功能名称说明",
        "Show Hidden Items": "显示临时收纳的图标",
        "Show Lock Screen Live Activity": "锁屏界面展示实时活动胶囊",
        "Show Notes in Notch Bar": "在刘海栏中显示便签入口",
        "Show Percentage": "显示精确百分比数值",
        "Show Section Dividers": "显示状态栏分区分隔条",
        "Show Spotify Tab": "显示 Spotify 专用控制面板",
        "Show Spotify, App & Device Icons": "同时显示来源应用与输出设备徽标",
        "Show Time Instead of Ring": "以倒计时数字代替环形进度条",
        "Show in Normal Volume HUD": "在常规系统音量指示器中显示",
        "Show popularity of track in music player": "在音乐播放器中展示歌曲热度",
        "Show track info on Track Change": "切歌时在刘海微展播报歌名",
        "Show update Live Activity": "发现新版本时在刘海弹出实时提示",
        "Skip Ads": "自动静音或跳过音频广告",
        "Spaces": "虚拟桌面空间 (Spaces)",
        "Spoof Detection": "活体防伪检测防照片盗刷",
        "Stats Configuration": "硬件数据源配置",
        "Step 1: Bring Device Close": "第一步：将已配对设备贴近 Mac",
        "Step 1: Calibrate 'Near' Distance": "第一步：校准「近场」感应距离",
        "Step 2: Calibrate 'Far' Distance": "第二步：校准「远场离开」感应距离",
        "Step 2: Move Device Far Away": "第二步：将设备拿远至离开工位",
        "Step 3: Select Your Device": "第三步：从列表选择您的随身设备",
        "Swipe Actions": "行项滑动手势操作",
        "Swipe to Dismiss": "向外轻扫忽略/关闭",
        "Sync with System Clock": "与系统时钟保持毫秒级同步",
        "System apps": "系统内建应用程序",
        "Top Info Widget": "顶部常驻信息小组件",
        "Turn Off Screen on Lock": "锁定时立刻息屏断电节电",
        "Unlimited History": "无上限保留全部剪贴板历史",
        "Update Preferences": "软件更新偏好设置",
        "Update notifications": "新版本发布通知",
        "Use Screensaver to Lock": "使用屏幕保护程序代替黑屏锁定",
        "Use on Desktop": "同步在桌面壁纸上启用",
        "Verification Codes": "短信与邮件验证码",
        "Wake on Proximity": "携带设备走近时自动唤醒屏幕",
        "Wake without Unlocking": "唤醒屏幕但等待密码或生物识别",
        "Wallpaper": "动态壁纸引擎",
        "Window Switcher": "多窗口快速切换器",
        "XDR Brightness": "XDR 峰值超感高亮",
        "XDR Brightness Lock": "锁定 XDR 亮度防止意外回落",
    ]
}

// MARK: - English Translations

enum EnglishTranslations {
    static let table: [String: String] = [
        "General": "General",
        "Notch": "Notch",
        "Widgets & Content": "Widgets & Content",
        "System & Utilities": "System & Utilities",
        "Focus & Security": "Focus & Security",
        "About": "About",
    ]
}
